# Generated by Django 2.2.4 on 2023-02-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='These are the old notes.', max_length=255),
            preserve_default=False,
        ),
    ]
